---
- name: 4.1 and 4.2 Maintain the OpenShift default permissions and file ownership for the API server pod 
  file:
    path: /etc/origin/node/pods/apiserver.yaml
    owner: root
    group: root
    state: file
    mode: 0600

- name: 4.3 and 4.4 Maintain the OpenShift default file permissions and file ownership for the controller manager pod specification file
  file:
    path: /etc/origin/node/pods/controller.yaml
    owner: root
    group: root
    state: file
    mode: 0600

- name: 4.5 and 4.6 Maintain the OpenShift default permissions and file ownership for the scheduler pod specification file
  file:
    path: /etc/origin/node/pods/controller.yaml
    owner: root
    group: root
    state: file
    mode: 0600

- name: 4.7 and 4.8 Maintain the OpenShift default etcd pod specification file permissions and file ownership
  file:
    path: /etc/origin/node/pods/etcd.yaml
    owner: root
    group: root
    state: file
    mode: 0600

- name: 4.11 and 4.12 Maintain the default OpenShift etcd data directory permissions and directory ownership
  file:
    path: /var/lib/etcd
    owner: etcd
    group: etcd
    state: directory
    mode: 0700

- name: 4.13 and 4.14 Maintain the default OpenShift admin.conf file permissions and file ownership
  file:
    path: /etc/origin/master/admin.kubeconfig
    owner: root
    group: root
    state: file
    mode: 0644

- name: 4.15, 4.16, 4.17 and 4.18 Maintain the default OpenShift scheduler.conf and controller-manager.conf file permissions and file ownership
  file:
    path: /etc/origin/master/openshift-master.kubeconfig
    owner: root
    group: root
    state: file
    mode: 0644
