- name: 5.1 Maintain the default OpenShift cert-file and key-file configuration
  lineinfile:
    path: /etc/etcd/etcd.conf
    regexp: '^ETCD_CERT_FILE=((?!/etc/etcd/server.crt).)*$'
    line: 'ETCD_CERT_FILE=/etc/etcd/server.crt'

- lineinfile:
    path: /etc/etcd/etcd.conf
    regexp: '^ETCD_KEY_FILE=((?!/etc/etcd/server.key).)*$'
    line: 'ETCD_KEY_FILE=/etc/etcd/server.key'

- name: 5.2 Maintain the default OpenShift setting for the client-cert-auth argument
  lineinfile:
    path: /etc/etcd/etcd.conf
    regexp: '^ETCD_CLIENT_CERT_AUTH=((?!true|TRUE).)*$'
    line: 'ETCD_CLIENT_CERT_AUTH=true'

- name: 5.3 Maintain the OpenShift default values for etcd_auto_tls
  lineinfile:
    path: /etc/etcd/etcd.conf
    regexp: '^ETCD_AUTO_TLS=((?!false|FALSE).)*$'
    line: 'ETCD_AUTO_TLS=false'

- name: 5.4 Maintain the OpenShift default peer-cert-file and peer-key-file arguments for etcd
  lineinfile:
    path: /etc/etcd/etcd.conf
    regexp: '^ETCD_PEER_CERT_FILE=((?!/etc/etcd/peer.crt).)*$'
    line: 'ETCD_PEER_CERT_FILE=/etc/etcd/peer.crt'

- lineinfile:
    path: /etc/etcd/etcd.conf
    regexp: '^ETCD_PEER_CLIENT_CERT_AUTH=((?!true|TRUE).)*$'
    line: 'ETCD_PEER_CLIENT_CERT_AUTH=true'

- name: 5.5 Maintain the OpenShift default configuration for the peer-client-cert-auth
  lineinfile:
    path: /etc/etcd/etcd.conf
    regexp: '^ETCD_PEER_CERT_FILE=((?!/etc/etcd/peer.crt).)*$'
    line: 'ETCD_PEER_CERT_FILE=/etc/etcd/peer.crt'

- name: 5.6 Maintain the OpenShift default configuration for the peer-auto-tls argument
  lineinfile:
    path: /etc/etcd/etcd.conf
    regexp: '^ETCD_PEER_AUTO_TLS=((?!false|FALSE).)*$'
    line: 'ETCD_PEER_AUTO_TLS=false'

# Note that 5.7 and 5.8 are omitted as they are removed from the CIS 1.3.0 benchmark

- name: 5.9 Maintain the OpenShift default configuration for the etcd Certificate Authority
  command: openssl x509 -in /etc/origin/master/master.etcd-ca.crt -subject -issuer -noout
