---
# tasks file for sdn-networkpolicy

- command: oc logion -u ocpadmin --config=/home/ec2-user/.kube/config

- command: oc get clusternetwork

- name: Change SDN to NetworkPolicy
  yedit:
    src: /etc/origin/master/master-config.yaml
    key: networkConfig.networkPluginName 
    value: redhat/openshift-ovs-networkpolicy
  state: present
